name: Pyright Workflow
on:
  workflow_dispatch:
jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      # - name: Install system dependencies
      #   run: |
      #     apt install -y adduser base-files bash bash-completion binutils-common:amd64 command-not-found coreutils cron-daemon-common debconf dhcpcd-base e2fsprogs fuse3 hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1t64:amd64 libmecab2:amd64 libpam-runtime libpython3.12-minimal:amd64 libpython3.12-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace man-db media-types multipath-tools nano netbase nftables openssl overlayroot procps python3.12-minimal rsyslog screen sudo tar tzdata ucf usb-modeswitch util-linux walinuxagent wget
      - name: Install Python packages
        run: |
          pip install pyright==1.1.408 setuptools==80.10.2
          python -m pip install --upgrade pip
          pip install pyright
      - name: Run Pyright
        run: |
          pyright . --level error
